---
- name: Deploy Docker container on EC2
  hosts: ec2-instance
  become: true

  vars_files:
    - secrets.yml

  tasks:
    - name: Update APT packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Log in to GHCR
      docker_login:
        registry: ghcr.io
        username: "{{ ghcr_username }}"
        password: "{{ ghcr_token }}"

    - name: Pull Docker image from GHCR
      docker_image:
        name: ghcr.io/donivanev/devops-automation/my-app
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: my-app
        image: ghcr.io/donivanev/devops-automation/my-app:latest
        state: started
        restart_policy: always
        published_ports:
          - "80:80"